"""
Generates docker-compose.generated.yml from instances.json configuration.
Creates services for managed databases, Odoo instances, nginx, and optionally pgAdmin.
"""

import os

from .config_loader import (
    resolve_instance_config,
    resolve_db_config,
    get_db_host,
    get_managed_databases,
    get_odoo_minor,
)

# Internal ports used by Odoo (never exposed directly; nginx proxies them)
ODOO_HTTP_PORT = 8069
ODOO_GEVENT_PORT = 8071

NETWORK_NAME = "odoo-multi"


def generate_compose(base_path, config, dockerfile_map):
    """
    Generate docker-compose.generated.yml.
    Returns the output file path.
    """
    lines = _header()

    # --- Database services ---
    managed_dbs = get_managed_databases(config)
    for db_name, db_conf in managed_dbs.items():
        lines += _db_service(db_name, db_conf)

    # --- Odoo instance services ---
    for inst_name, inst_conf in config["instances"].items():
        odoo_conf = resolve_instance_config(inst_conf, config)
        db_conf = resolve_db_config(inst_conf, config)
        db_name = inst_conf["database"]
        odoo_version = inst_conf["odoo_version"]
        dockerfile = dockerfile_map[odoo_version]
        lines += _odoo_service(
            inst_name, inst_conf, odoo_conf, db_name, db_conf, dockerfile
        )

    # --- Nginx service ---
    lines += _nginx_service(config)

    # --- pgAdmin service (optional) ---
    pgadmin_conf = config.get("pgadmin", {})
    if pgadmin_conf.get("enabled", False):
        lines += _pgadmin_service(pgadmin_conf)

    # --- Volumes ---
    lines += _volumes(config)

    # --- Networks ---
    lines += _networks()

    output_path = os.path.join(base_path, "docker-compose.generated.yml")
    with open(output_path, "w") as f:
        f.write("\n".join(lines))
        f.write("\n")

    print(f"  docker-compose.generated.yml generado")
    return output_path


def _header():
    return [
        "# Auto-generated by ./odoo build — DO NOT EDIT MANUALLY",
        "# Modify instances.json and run ./odoo build to regenerate",
        "",
        "services:",
    ]


def _db_service(db_name, db_conf):
    pg_version = db_conf["postgres_version"]
    port = db_conf["port"]
    user = db_conf["user"]
    password = db_conf["password"]
    pg_config = db_conf.get("config")
    container_name = f"db-{db_name}"

    lines = [
        f"  {container_name}:",
    ]

    if pg_config:
        lines += [
            f'    command: ["postgres", "-c", "config_file=/etc/postgres/dbconfigs/{pg_config}"]',
        ]

    lines += [
        "    restart: always",
        f"    container_name: {container_name}",
        "    build:",
        "      context: .",
        "      dockerfile: ./.resources/db.Dockerfile",
        "      args:",
        f"        POSTGRES_IMG_VERSION: {pg_version}",
        f"    image: local_odoo_db_{db_name}:{pg_version}",
        "    ports:",
        f'      - "{port}:5432"',
        f"    networks:",
        f"      - {NETWORK_NAME}",
        "    volumes:",
        "      - ./.resources/dbconfigs:/etc/postgres/dbconfigs",
        f"      - {db_name}-data:/var/lib/postgresql/data",
        "    environment:",
        "      - POSTGRES_DB=postgres",
        f"      - POSTGRES_PASSWORD={password}",
        f"      - POSTGRES_USER={user}",
        "      - PGDATA=/var/lib/postgresql/data/pgdata",
        "",
    ]
    return lines


def _odoo_service(inst_name, inst_conf, odoo_conf, db_name, db_conf, dockerfile):
    odoo_version = inst_conf["odoo_version"]
    odoo_minor = get_odoo_minor(odoo_version)
    container_name = f"odoo-{inst_name}"
    db_host = get_db_host(db_name, db_conf)
    db_port = db_conf["port"]
    db_user = db_conf["user"]
    db_password = db_conf["password"]

    # Build addons list for INSTANCE_ADDONS env var
    addons = odoo_conf.get("addons", [])
    addons_str = ",".join(addons) if addons else ""

    # Determine depends_on
    depends = []
    if db_conf.get("create_container", True):
        depends.append(f"db-{db_name}")

    lines = [
        f"  {container_name}:",
        "    command: odoo --dev=all",
        "    restart: always",
        f"    container_name: {container_name}",
        "    build:",
        "      context: .",
        f"      dockerfile: ./{dockerfile}",
        f"    image: local_odoo_{inst_name}:{odoo_minor}",
        "    extra_hosts:",
        '      - "host.docker.internal:host-gateway"',
        "    dns:",
        "      - 8.8.8.8",
        "      - 1.1.1.1",
        f"    networks:",
        f"      - {NETWORK_NAME}",
    ]

    if depends:
        lines.append("    depends_on:")
        for dep in depends:
            lines.append(f"      - {dep}")

    lines += [
        "    volumes:",
        f"      - {inst_name}-web:/var/lib/odoo",
        "      - ./src:/home/odoo/src",
        "      - ./.resources/.coveragerc:/home/odoo/.coveragerc",
        f"      - {inst_name}-data:/home/odoo/data",
        f"      - {inst_name}-py3:/usr/local/lib/",
        f"      - {inst_name}-py:/usr/lib/",
        "    environment:",
    ]

    # Custom config from odoo_conf
    custom_config = odoo_conf.get("custom_config", "[options]")
    lines.append(f"      CUSTOM_CONFIG: |-")
    for config_line in custom_config.split("\n") if isinstance(custom_config, str) else ["[options]"]:
        lines.append(f"        {config_line}")

    lines += [
        "      CUSTOM_REQUIREMENTS: |-",
        "        # custom pip libraries",
        "      CUSTOM_ENTRYPOINT: |-",
        "        #!/bin/bash",
        f"      GEVENT_PORT: {ODOO_GEVENT_PORT}",
        f"      DB_HOST: {db_host}",
        f"      DB_PORT: {db_port}",
        f"      PGUSER: {db_user}",
        f"      PGPASSWORD: {db_password}",
        f"      PGHOST: {db_host}",
        f"      PGPORT: {db_port}",
        f"      ADMIN_PASSWORD: {odoo_conf.get('admin_password', 'admin')}",
        "      SMTP_SERVER: mailhog",
        "      SMTP_PORT: 1025",
        f"      DBFILTER: {odoo_conf.get('db_filter', '')}",
        f"      SERVER_WIDE_MODULES: {odoo_conf.get('server_wide_modules', '')}",
        f"      WORKERS: {odoo_conf.get('workers', 2)}",
        f"      LIST_DB: {odoo_conf.get('list_db', True)}",
        f"      DB_NAME: {odoo_conf.get('db_name', 'False')}",
        f"      WITHOUT_DEMO: {odoo_conf.get('without_demo', True)}",
        f"      PROXY_MODE: {odoo_conf.get('proxy_mode', True)}",
        f"      SERVER_MODE: {odoo_conf.get('server_mode', 'test')}",
        f"      AEROO_DOCS_HOST: {odoo_conf.get('aeroo_docs_host', 'aeroo')}",
        f"      UNACCENT: {odoo_conf.get('unaccent', False)}",
        "      LOG_LEVEL: info",
        f"      LIMIT_MEMORY_SOFT: {odoo_conf.get('limit_memory_soft', 16000000000)}",
        f"      LIMIT_MEMORY_HARD: {odoo_conf.get('limit_memory_hard', 17000000000)}",
        f"      MAX_CRON_THREADS: {odoo_conf.get('max_cron_threads', 1)}",
        f"      LIMIT_TIME_REAL_CRON: {odoo_conf.get('limit_time_real_cron', 0)}",
        f"      LIMIT_TIME_REAL: {odoo_conf.get('limit_time_real', 3600)}",
        f"      LIMIT_TIME_CPU: {odoo_conf.get('limit_time_cpu', 60)}",
        f"      DB_MAXCONN: {odoo_conf.get('db_maxconn', 200)}",
    ]

    # INSTANCE_ADDONS: used by the modified 400-auto-detect-addons entrypoint
    if addons_str:
        lines.append(f"      INSTANCE_ADDONS: \"{addons_str}\"")

    lines.append("")
    return lines


def _nginx_service(config):
    """Generate nginx service that maps all instance external ports."""
    all_ports = [
        inst["external_port"]
        for inst in config["instances"].values()
    ]
    odoo_containers = [
        f"odoo-{name}" for name in config["instances"]
    ]

    lines = [
        "  nginx:",
        "    restart: always",
        "    container_name: odoo-nginx",
        "    image: nginx:latest",
        # "    depends_on:",
    ]
    # for container in odoo_containers:
    #     lines.append(f"      - {container}")

    lines += [
        "    extra_hosts:",
        '      - "host.docker.internal:host-gateway"',
        "    ports:",
    ]
    for port in all_ports:
        lines.append(f'      - "{port}:{port}"')

    lines += [
        f"    networks:",
        f"      - {NETWORK_NAME}",
        "    volumes:",
        "      - ./.resources/nginx_configs/generated.conf:/etc/nginx/conf.d/default.conf",
        "",
    ]
    return lines


def _pgadmin_service(pgadmin_conf):
    port = pgadmin_conf.get("port", 5050)
    email = pgadmin_conf.get("email", "admin@admin.com")
    password = pgadmin_conf.get("password", "admin")

    return [
        "  pgadmin:",
        "    image: dpage/pgadmin4:latest",
        "    container_name: odoo-pgadmin",
        "    restart: always",
        "    environment:",
        f"      PGADMIN_DEFAULT_EMAIL: {email}",
        f"      PGADMIN_DEFAULT_PASSWORD: {password}",
        "    extra_hosts:",
        '      - "db:host-gateway"',
        "    ports:",
        f'      - "{port}:80"',
        f"    networks:",
        f"      - {NETWORK_NAME}",
        "    volumes:",
        "      - pgadmin-data:/var/lib/pgadmin",
        "",
    ]


def _volumes(config):
    lines = [
        "volumes:",
    ]

    # DB volumes
    managed_dbs = get_managed_databases(config)
    for db_name in managed_dbs:
        lines.append(f"  {db_name}-data:")

    # Instance volumes
    for inst_name in config["instances"]:
        lines.append(f"  {inst_name}-web:")
        lines.append(f"  {inst_name}-data:")
        lines.append(f"  {inst_name}-py3:")
        lines.append(f"  {inst_name}-py:")

    # pgAdmin volume
    pgadmin_conf = config.get("pgadmin", {})
    if pgadmin_conf.get("enabled", False):
        lines.append("  pgadmin-data:")

    lines.append("")
    return lines


def _networks():
    return [
        "networks:",
        f"  {NETWORK_NAME}:",
        "    driver: bridge",
        "",
    ]
